version: "3.7"

services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: backend
    ports:
      - 5000:5005
    command: python app.py
    restart: always
    depends_on:
      - redis

  worker:
    image: backend
    command: python worker.py
    restart: always
    depends_on:
      - redis
      - web

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: frontend
    ports:
      - 3000:3000
    command: npm start
    restart: always
    links:
      - web

  redis:
    image: redis:5.0.7-alpine
