version: "3.7"

services:
  web:
    image: backend
    ports:
      - 5000:5005
    command: python app.py
    restart: always
    depends_on:
      - redis

  worker:
    image: backend
    command: python worker.py
    restart: always
    depends_on:
      - redis

  ui:
    build:
      contex: ./ui
      dockerfile: Dockerfile.prod
    ports:
      - 3000:80
    restart: always
    links:
      - web

  redis:
    image: redis:5.0.7-alpine
