version: "3.7"

services:
  web:
    image: backend
    ports:
      - 5000:5005
    command: python app.py
    depends_on:
      - redis

  worker:
    image: backend
    command: python worker.py
    depends_on:
      - redis

  redis:
    image: redis:5.0.7-alpine
